columnSuffix: null
handle: colour
instructions: 'The colour of the element'
name: Colour
searchable: false
settings:
  allowCustomColors: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
