altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  598e2d4a-c400-4ccd-a4a2-2dbcc30944f8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-02-24T22:36:12+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: fe23a6f1-0ea0-40d0-938d-680290ebf66f
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-02-24T22:39:38+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: bfa8ff0a-8978-4318-b22b-8d320ab59dc0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d29a5e50-bed2-4f24-820c-68526b801403
        userCondition: null
fs: assets
handle: images
name: Images
sortOrder: 3
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: assets
transformSubpath: ''
