baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: 'Destination Explorer'
primary: true
siteGroup: 1718735a-958d-412d-89f5-7c112232edff # mywebsite
sortOrder: 1
